version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tenant-app
    env_file:
      - .env
    ports:
      - "127.0.0.1:3034:3034"   # hanya dapat diakses dari host
    restart: unless-stopped
